import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import { CssBaseline, ThemeProvider } from "@mui/material";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import theme from "./theme";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Contact Directory",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <AppRouterCacheProvider>
           <ThemeProvider theme={theme}>
              <CssBaseline />
                <Providers>
                  {children}
                </Providers>
           </ThemeProvider>
          </AppRouterCacheProvider>
        </body>
    </html>
  );
}
